name: "my_server_pro"
server_config:
  host: "127.0.0.1"
  port: 7788
mysql_config:
  user: ""
  pwd: ""
  host: ""
  port: ""
  dbname: ""
  arguments: ""
redis_config:
  addr: ""
  pass_word: ""
rmq_config:
  user: ""
  pwd: ""
  host: ""
  port: ""
consul_config:
  addr: ""
  service:
    name: ""
    tags: ["","",""]