nacos:
  server:
    host: ""
    port: 8848
    context_path: ""
  client:
    namespace_id: ""
    timeout_ms: 5000
    not_load_cache_at_start: true
    log_dir: ""
    cache_dir: ""
    log_level: ""
  data:
    group: "dev"
    data_id: "config_dev.yaml"
    type: "yaml"